spring:
  application:
    name: PatrimonioRSAPI   
  profiles:
    active: dev


server:
  port: 8090
  servlet:
    context-path: /patrimonio
    
---

spring:
  config:
    activate:
      on-profile: dev 
  #mvc.pathmatch.matching-strategy: ANT_PATH_MATCHER 
  data:
    mongodb:
      uri: mongodb://localhost:28017/Poste?retryWrites=true&w=majority # Set this to mongodb connection string

#spring.main.allow-circular-references: true 



logging:
  level:
    org:
      springframework:
        web: DEBUG
        data: DEBUG
    root: INFO
