spring:
  application:
    name: PatrimonioRSAPI   
  profiles:
    active: dev


server:
  port: 8090
  servlet:
    context-path: /patrimonio
    
---

spring:
  config:
    activate:
      on-profile: dev 
  data:
    mongodb:
      uri: mongodb://localhost:28017/Poste?retryWrites=true&w=majority # Set this to mongodb connection string
      auto-index-creation: true

logging:
  level:
    org:
      springframework:
        web: DEBUG
        data: DEBUG
    root: INFO
