spring:
  application:
    name: PatrimonioBatch  
  profiles:
    active: dev
    
---

spring:
  config:
    activate:
      on-profile: dev 
  #mvc.pathmatch.matching-strategy: ANT_PATH_MATCHER 
  data:
    mongodb:
      uri: mongodb://localhost:28017/Poste?retryWrites=true&w=majority # Set this to mongodb connection string
      dbname: Poste     
  datasource:
      url: jdbc:postgresql://localhost:5433/postgres
      username: postgres
      password: password
      driver-class-name: org.postgresql.Driver
      hikari:
         connection-timeout: 60000
  batch:
      jdbc:
         initialize-schema: always
      job:
         enabled: true

#spring.main.allow-bean-definition-overriding: true

#spring.main.allow-circular-references: true 



logging:
  level:
    org:
      springframework:
        data: DEBUG
    root: INFO
    

