spring:
  profiles:
    active: dev
  application:
    name: PatrimonioKConsumer
  kafka:
    producer:
      transaction-id-prefix: tx-
      acks: all
      properties:
        enable:
          idempotence: true
    consumer:
      enable-auto-commit: true
      properties:
        isolation:
          level: read_committed

patrimonio:
  kafka:
    group-id: patrimonio
    topic:
      gpmgoe:
        cdc-events: gpmfoe_cdc_events
        business-events: gpmfoe_business_events
      titoli:
        cdc-events: titoli_cdc_events
        business-events: titoli_business_events


