spring:
  application:
    name: PatrimonioKConsumer 
  profiles:
    active: poste
  kafka:
    producer:
      transaction-id-prefix: tx-
      acks: all
      properties:
        enable:
          idempotence: true

    consumer:
      enable-auto-commit: true
      properties:
        isolation:
          level: read_committed

server:
  port: 8091
  servlet:
    context-path: /patrimonio
        
---

spring:
  config:
    activate:
      on-profile: dev 
  data:
    mongodb:
      uri: mongodb://localhost:28017/Poste?retryWrites=true&w=majority # Set this to mongodb connection string
      dbName: Poste
kafka:
  bootstrapAddress: localhost:9092 #set this to your kafka bootstrap server
  groupId: test
  jaas: org.apache.kafka.common.security.plain.PlainLoginModule required username='' password='; # Set this if you are using authentication
  topicName: kafka-mongo-integration
  consumer:
    backOff:
      interval: 500
      maxAttempts: 2
    concurrency: 5
  
logging:
  level:
    org:
      springframework:
        data: debug
        kafka:
          transaction: trace
          
---

spring:
  config:
    activate:
      on-profile: poste 
  data:
    mongodb:
      uri: mongodb://localhost:28017/Poste?retryWrites=true&w=majority # Set this to mongodb connection string
      dbName: Poste
kafka:
  bootstrapAddress: kafka2.coll.testposte:9092 #set this to your kafka bootstrap server
  groupId: test4
  jaas: org.apache.kafka.common.security.plain.PlainLoginModule required username='' password='; # Set this if you are using authentication
  topicName: idrkafka.titoordr.sourcedb.fiaf0001.dfina0c.a2tordr-json
  consumer:
    backOff:
      interval: 500
      maxAttempts: 2
    concurrency: 5
  
logging:
  level:
    org:
      springframework:
        data: debug
        kafka:
          transaction: trace

