
spring:
  data:
    mongodb:
      uri: mongodb://localhost:28017/Poste?retryWrites=true&w=majority # Set this to mongodb connection string
      dbName: Poste

kafka:
  bootstrapAddress: kafka2.coll.testposte:9092 #set this to your kafka bootstrap server
  groupId: test8
  jaas: org.apache.kafka.common.security.plain.PlainLoginModule required username='' password='; # Set this if you are using authentication
  topicName: idrkafka.titoordr.sourcedb.fiaf0001.dfina0c.a2tordr-json
  consumer:
    backOff:
      interval: 500
      maxAttempts: 2
    concurrency: 10

server:
  port: 8091
  servlet:
    context-path: /patrimonio

logging:
  level:
    org:
      springframework:
        data: debug
        kafka:
          transaction: trace